[package]
name = "dancelist"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.11.0"
axum = "0.4.4"
chrono = { version = "0.4.19", features = ["serde"] }
color-backtrace = "0.5.1"
eyre = "0.6.6"
log = "0.4.14"
pretty_env_logger = "0.4.0"
serde = { version = "1.0.136", features = ["derive"] }
stable-eyre = "0.2.2"
tokio = { version = "1.15.0", features = ["macros", "rt-multi-thread"] }
toml = "0.5.8"
