[package]
name = "dancelist"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Andrew Walbran <qwandor@gmail.com>"]
description = "A website for listing folk dance events."
repository = "https://github.com/qwandor/dancelist"
keywords = ["folk", "dance", "balfolk", "website"]
categories = ["web-programming"]

[dependencies]
askama = "0.11.0"
axum = "0.4.4"
chrono = { version = "0.4.19", features = ["serde"] }
color-backtrace = "0.5.1"
eyre = "0.6.6"
log = "0.4.14"
pretty_env_logger = "0.4.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.8.23"
stable-eyre = "0.2.2"
tokio = { version = "1.15.0", features = ["macros", "rt-multi-thread"] }
toml = "0.5.8"
tower-http = { version = "0.2.1", features = ["fs"] }

[package.metadata.deb]
section = "web"
maintainer-scripts = "debian-scripts"
conf-files = ["/etc/dancelist.toml"]
assets = [
	["target/release/dancelist", "usr/bin/", "755"],
	["public/stylesheets/*", "/usr/share/dancelist/stylesheets/", "644"],
	["dancelist.example.toml", "etc/dancelist.toml", "640"],
]

# This section needs to be here even if it's empty, for the systemd integration to work.
[package.metadata.deb.systemd-units]
