# For running directly from the source directory, set this to "public" or omit it.
public_dir = "/usr/share/dancelist"

# The directory from which to read events data. This will probably be from the dancelist-data
# repository.
events_dir = "/var/lib/dancelist"

# The address on which the server should listen.
bind_address = "0.0.0.0:3002"
