[[events]]
name = "Balfolk Dansstage 2022"
start_date = "2022-03-18"
end_date = "2022-03-20"
links = ["https://dansstage.nl/", "https://www.facebook.com/events/4532218756868340/"]
country = "Netherlands"
city = "Enschede"
styles = ["Balfolk"]
workshop = true
social = true
price = "€115-€210"
organisation = "Dansstage"
