[[events]]
name = "Bals et Roses"
start_date = "2022-06-24"
end_date = "2022-06-26"
links = ["https://www.festivalbalsetroses.be/"]
country = "Belgium"
city = "Florenville"
styles = ["Balfolk"]
workshop = true
social = true
organisation = "Bals et Roses"
