[[events]]
name = "Boombalfestival"
start_date = "2022-08-25"
end_date = "2022-08-28"
links = ["https://boombalfestival.be/home"]
country = "Belgium"
city = "Lovendegem"
styles = ["Balfolk"]
workshop = true
social = true
organisation = "Boombal"
