[[events]]
name = "Brighton Gender-Free Contra"
start_date = "2022-02-23"
end_date = "2022-02-23"
links = ["https://www.facebook.com/events/1345685155869599/"]
country = "UK"
city = "Brighton"
styles = ["contra"]
workshop = false
social = true
bands = ["Linda Game Trio"]
callers = ["Louise Siddons"]
price = "£2-£10"
organisation = "Brighton Gender-Free Contra"
