[[events]]
name = "Bristol Contra Dance"
start_date = "2022-02-18"
end_date = "2022-02-18"
links = ["https://bristolcontra.wordpress.com/", "https://www.facebook.com/events/690727345267580/"]
country = "UK"
city = "Bristol"
styles = ["contra"]
workshop = false
social = true
bands = ["Bearded Dragons"]
callers = ["Charlotte Rich-Griffin"]
price = "£6-£15"
organisation = "Bristol Contra"

[[events]]
name = "Bristol Contra Dance"
start_date = "2022-03-25"
end_date = "2022-03-25"
links = ["https://bristolcontra.wordpress.com/"]
country = "UK"
city = "Bristol"
styles = ["contra"]
workshop = false
social = true
bands = []
callers = []
price = "£6-£15"
organisation = "Bristol Contra"

[[events]]
name = "Bristol Contra Dance"
start_date = "2022-04-22"
end_date = "2022-04-22"
links = ["https://bristolcontra.wordpress.com/"]
country = "UK"
city = "Bristol"
styles = ["contra"]
workshop = false
social = true
bands = []
callers = []
price = "£6-£15"
organisation = "Bristol Contra"

