[[events]]
name = "Bal Folk Dancing at the Jam Jar"
details = "An informal, indoor gathering with European folk music and social dancing."
links = ["https://www.facebook.com/events/1542560522772557"]
country = "UK"
city = "Bristol"
styles = ["Balfolk"]
workshop = true
social = true
price = "donation"
organisation = "BalFolk Bristol"
