[[events]]
name = "Bal Folk Dancing at the Jam Jar"
details = "An informal, indoor gathering with European folk music and social dancing."
start_date = "2022-02-05"
end_date = "2022-02-05"
links = ["https://www.facebook.com/events/1542560522772557/"]
country = "UK"
city = "Bristol"
styles = ["balfolk"]
workshop = true
social = true
price = "donation"
organisation = "BalFolk Bristol"

[[events]]
name = "Bal Folk Dancing at the Jam Jar"
details = "An informal, indoor gathering with European folk music and social dancing."
start_date = "2022-03-26"
end_date = "2022-03-26"
links = ["https://www.facebook.com/events/1542560519439224/"]
country = "UK"
city = "Bristol"
styles = ["balfolk"]
workshop = true
social = true
price = "donation"
organisation = "BalFolk Bristol"
