[[events]]
name = "Folk Festival Leuven - ComSiBal"
details = "The 2nd edition of the Folk Festival Leuven."
start_date = "2022-04-15"
end_date = "2022-04-17"
links = ["https://www.facebook.com/events/629470541604750/"]
country = "Belgium"
city = "Leuven"
styles = ["Balfolk", "Scandinavian"]
workshop = true
social = true
bands = ["Lyra Danz", "Duo Mackie/Hendrix", "Trio14", "Duo Besson-Rio", "Beat Bouet Trio", "Emmarilin", "Duo Tanghe-Coudroy", "Floris & the Flames", "Duo Zena", "Duo Balzam"]
organisation = "ComSiBal"
