[[events]]
name = "Grand Bal de l'Europe (Gennetines)"
start_date = "2022-07-22"
end_date = "2022-08-05"
links = ["https://www.gennetines.org/2021/12/grand-bal-de-leurope-2022/"]
country = "France"
city = "Gennetines"
styles = ["Balfolk"]
workshop = true
social = true
