[[events]]
name = "London Barndance with Mark Elvins and English Contra Dance Band"
details = "Contra dance with Mark Elvins calling and the English Contra Dance Band playing."
links = ["https://www.barndance.org/programme.html", "https://www.facebook.com/events/243417821143957/"]
country = "UK"
city = "London"
styles = ["Contra"]
workshop = false
social = true
bands = ["English Contra Dance Band"]
callers = ["Mark Elvins"]
price = "£5-£14"
organisation = "London Barndance Company"

[[events]]
name = "London Barndance with Louise Siddons and Portland Drive"
details = "Contra dance with Louise Siddons calling and Portland Drive playing."
links = ["https://www.barndance.org/programme.html"]
country = "UK"
city = "London"
styles = ["Contra"]
workshop = false
social = true
bands = ["Portland Drive"]
callers = ["Louise Siddons"]
price = "£5-£14"
organisation = "London Barndance Company"
