[[events]]
name = "Folk Weekend Mattstedt"
start_date = "2022-06-23"
end_date = "2022-06-26"
links = ["https://www.muehlenhofmattstedt.de/folk-festival"]
country = "Germany"
city = "Mattstedt"
styles = ["Balfolk"]
workshop = true
social = true
bands = ["Wings and Tales", "Flowers", "Bargainatt", "J.B. Picot", "Maracu"]
price = "€25-€135"
organisation = "Mühlenhof Mattstedt"
