[[events]]
name = "On Bouge"
start_date = "2022-02-11"
end_date = "2022-02-11"
links = ["https://onbouge.org/"]
country = "UK"
city = "London"
styles = ["Balfolk"]
workshop = false
social = true
bands = ["Sawney White Bird"]
organisation = "On Bouge"

[[events]]
name = "On Bouge"
start_date = "2022-03-12"
end_date = "2022-03-12"
links = ["https://onbouge.org/"]
country = "UK"
city = "London"
styles = ["Balfolk"]
workshop = true
social = true
organisation = "On Bouge"

[[events]]
name = "On Bouge"
start_date = "2022-04-08"
end_date = "2022-04-08"
links = ["https://onbouge.org/"]
country = "UK"
city = "London"
styles = ["Balfolk"]
workshop = false
social = true
organisation = "On Bouge"

[[events]]
name = "On Bouge"
start_date = "2022-05-13"
end_date = "2022-05-13"
links = ["https://onbouge.org/"]
country = "UK"
city = "London"
styles = ["Balfolk"]
workshop = false
social = true
organisation = "On Bouge"

[[events]]
name = "On Bouge"
start_date = "2022-06-10"
end_date = "2022-06-10"
links = ["https://onbouge.org/"]
country = "UK"
city = "London"
styles = ["Balfolk"]
workshop = false
social = true
organisation = "On Bouge"

[[events]]
name = "On Bouge"
start_date = "2022-07-08"
end_date = "2022-07-08"
links = ["https://onbouge.org/"]
country = "UK"
city = "London"
styles = ["Balfolk"]
workshop = false
social = true
organisation = "On Bouge"
