[[events]]
name = "Balfolk Ratisbonne"
start_date = "2022-04-07"
end_date = "2022-04-10"
links = ["https://www.balfolk-ratisbonne.net/"]
country = "Germany"
city = "Regensburg"
styles = ["balfolk"]
workshop = true
social = true
