[[events]]
name = "Contra Dance in Sheffield with Contrasaurus"
details = "This special one-off event is being organised by Contrasaurus in partnership with our friends at Sheffield Scratch Contra."
start_date = "2022-07-02"
end_date = "2022-07-02"
links = ["https://www.facebook.com/events/624541988872392/"]
country = "UK"
city = "Sheffield"
styles = ["contra"]
workshop = false
social = true
bands = ["Contrasaurus"]
callers = ["Charlotte Rich-Griffin", "Rachel Shapiro-Wallace"]
price = "£10"
organisation = "Sheffield Scratch Contra"
